//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Reviews = new HashSet<Review>();
        }
    
        public int companyID { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string licensing { get; set; }
        public string address { get; set; }
        public string phone2 { get; set; }
        public string companyName { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
        public Nullable<System.DateTime> dateModified { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public double StarRatting { get; set; }
        public int NoOfReviews { get; set; }
        public string SlugCompanyName { get; set; }
    
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
