//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public long reviewId { get; set; }
        public int companyId { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string quoteId { get; set; }
        public Nullable<int> cost { get; set; }
        public string pu_city { get; set; }
        public string pu_state { get; set; }
        public string de_city { get; set; }
        public string de_state { get; set; }
        public Nullable<int> rating { get; set; }
        public string summary { get; set; }
        public Nullable<bool> emailConfirmed { get; set; }
        public string review { get; set; }
        public Nullable<System.Guid> uniqueKey { get; set; }
        public string year { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> adminModerated { get; set; }
        public Nullable<bool> adminApproved { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
